# fly.toml app configuration file generated for res0nat0r-factorio on 2024-08-18T23:54:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'res0nat0r-factorio'
primary_region = 'atl'

[build]

[[mounts]]
  source = 'factorio'
  destination = '/factorio'

[[services]]
  protocol = 'udp'
  internal_port = 34197
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 34197

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
